name: roads
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
  
on: push

jobs:
  build:
    name: roadMaps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: print Current Directory
        run: pwd
      - name: install
        run: dotnet build
      - name: list files 
        run: ls TrickingLibarary.Api\ -R
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔍 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"